name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checks out code on the runner (not the server)

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. Create directory (if it doesn't exist)
            mkdir -p /home/Precious/fastapi-book-project

            # 2. Navigate to the directory
            cd /home/Precious/fastapi-book-project

            # 3. Clone or pull the repository (handling initial clone vs. updates)
            if [ ! -d ".git" ]; then  # Check for .git directory
              git clone https://github.com/P3dmund/fastapi-book-project.git . # Clone into the current directory
            else
              git pull origin main  # Update existing repository
            fi

            # 4. Docker Compose commands (assuming docker-compose.yml is in the repo)
            docker-compose down
            docker-compose up -d --build
